filebeat.inputs:
  - type: filestream
    id: filebeat-log
    paths:
      - "/var/lib/docker/containers/*/*.log"
    prospector.scanner.fingerprint.length: 128
    parsers:
      - container: ~

processors:
  - add_host_metadata: {}

  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  - drop_event:
      when:
        not:
          or:
            - equals:
                container.labels.log_enabled: "true"
            - equals:
                container.name: "${ALLOW_LOG_FROM_CONTAINER_1}"
            - equals:
                container.name: "${ALLOW_LOG_FROM_CONTAINER_2}"
            - equals:
                container.name: "${ALLOW_LOG_FROM_CONTAINER_3}"

  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      add_error_key: true

  - add_fields:
      target: ""
      fields:
        service: "unknown-service"
      when:
        not:
          has_fields: ["service"]

  - drop_fields:
      fields: ["agent", "ecs", "input", "log", "host", "container.id"]
      ignore_missing: true

setup.template.name: "logs"
setup.template.pattern: "logs-*"
setup.template.enabled: false
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "${ELASTICSEARCH_PASSWORD}"
  index: "logs-%{[service]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false
